version: '2'
services:
  redis:
    image: kbqallan/redis:5.0.2
    restart: always
    privileged: true
    container_name: redis_server
    network_mode: "host"
    ports:
    - 6379:6379
    - 26379:26379
    environment:
    - TERM=linux
    volumes:
    - /usr/share/zoneinfo/Etc/GMT+4:/etc/localtime:ro
#    - /etc/redis/redis.conf:/etc/redis.conf
    - /data/redis-data:/data/redis
