version: '2'

services:
  redis:
    build:
      context: https://github.com/xiaoyawl/docker-redis.git
    container_name: redis
    command: ["redis-server", "/etc/redis.conf"]
    restart: always
    privileged: true
    image: benyoo/redis:3.2.3
    environment:
    - TERM=linux
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/gitlab/redis.conf:/etc/redis.conf:ro
    - /data/gitlab/redis:/data/redis:Z
