version: '2'

services:
  redis:
    build:
      context: http://git.dwhd.org/lookback/docker-redis.git
    restart: always
    privileged: true
    image: redis:3.2.1
    ports:
    - "6379:6379"
    volumes:
    - /data/redis:/data/:Z
    - /etc/localtime:/etc/localtime
